### ISSUE TITLE
SSR example?

### ISSUE THREAD

**Issue by bfontaine** [HenryLie/svelte-i18n-lingui#9]
Hello,
Thank you for this library. Would you happen to have an example with SSR? I struggle to make it work with my app because of the shared store situation (see https://github.com/cibernox/svelte-intl-precompile/issues/39).

**Comment by HenryLie** [comment]
Hey @bfontaine, sorry for the late reply. I don't have much experience with SSR, but here is my understanding of the issue:
- We shouldn't use any shared store on the server since it'll get shared across requests, potentially made by different users
- The above recommendation seem to be mostly related to load function code, and not svelte component code. Since servers are stateless and the load function is executed in every request, we shouldn't try to access stores on load functions, but usage in components doesn't seem to be an issue (the component will import the store and will be rendered on the server using the default language).

Therefore, as long as we don't access the store in any load function, the lib should be working just fine with SSR enabled?
I tried building a very simple SSR example in this repo in the beta ([next](https://github.com/HenryLie/svelte-i18n-lingui/tree/v0.2.0-next)) branch. You can check out the branch and run `npm run dev` to try it out, the next branch has some api difference to the release version but the same approach should be applicable to the release version as well . 

In the sample code, a server load function runs on the very first page request since it's on the root layout, gets the browser's preferred language and returns this value to the component. The component then reads this from the page data, sets the preferred language to the store, then shows the page to the user with the preferred language. Does this match your use case?

**Comment by bfontaine** [comment]
Hello, sorry for my late reply as well. Thank you, it makes sense. The thing I’m missing is that I can’t mark text for translation outside of components, in the server-side code, like I would do using [lazy strings in Flask-Babel](https://python-babel.github.io/flask-babel/#:~:text=you%20can%20use%20a%20lazy%20strings.%20Lazy%20strings%20will%20not%20be%20evaluated%20until%20they%20are%20actually%20used.).
